language: elixir
elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.6
otp_release:
  - 20.3
  - 21.0
services: docker
notifications:
  recipients:
    - elixmoon@gmail.com
    - jquadrin@gmail.com
sudo: false
env:
    global:
        - MDBSOCKET=/var/run/mysqld/mysqld.sock
    matrix:
        - DB=mariadb:10.1 JSON_SUPPORT=false
        - DB=mariadb:10.2 JSON_SUPPORT=false
        - DB=mariadb:10.3 JSON_SUPPORT=false GEOMETRY_SUPPORT=false
        - DB=mysql:8.0 JSON_SUPPORT=true
        - DB=mysql:5.7 JSON_SUPPORT=true
        - DB=mysql:5.6 JSON_SUPPORT=false
matrix:
  include:
    - elixir: 1.4.5
      otp_release: 19.3
      env: DB=mysql:8.0 JSON_SUPPORT=true
    - elixir: 1.5.1
      otp_release: 19.3
      env: DB=mysql:5.7 JSON_SUPPORT=true
  exclude:
    - elixir: 1.4.5
      otp_release: 21.0
    - elixir: 1.5.3
      otp_release: 21.0
before_install:
    - sudo service mysql stop
    - docker pull $DB || true
    - docker run --name mariadb -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -d $DB --default-authentication-plugin=mysql_native_password
script: "JSON_SUPPORT=$JSON_SUPPORT mix test --cover"
